spring:
  application:
    name: springai-demo2
  ai:
    #    ollama:
    #      base-url: http://localhost:11434
    #      chat:
    #        model: qwen2.5:0.5b
    # ?? OpenAI API ???????
    openai:
      api-key: ${OPENAI_API_KEY:sk-ff26a51b7043407d8d68e49404b15944}
      # ??????????????????????base-url
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: qwen-plus  # ?????????
  cassandra:
    port: 8080