spring:
  application:
    name: springai-demo2
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your_api_key_here}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen3-vl-plus
  cassandra:
    port: 8080